version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### Workspace Utilities ##################################
  workspace:
    build: ./workspace
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - WORKSPACE_NCPU=${WORKSPACE_NCPU}
      - WORKSPACE_MEMORY=${WORKSPACE_MEMORY}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/pbf:${APP_CODE_PATH_CONTAINER}/pbf
      - ./workspace/mapping.yml:/etc/imposm/mapping.yml
      - ./workspace/osm-initial-import.sh:/usr/bin/osm-initial-import

    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    networks:
      - frontend
      - backend

### Katotherian ##################################
  kartotherian:
    build: ./kartotherian
    ports:
      - "6533:6533"
      - "16534:16534"
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
      - PGHOST=postgres-postgis
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      - workspace
      - postgres-postgis
      - cassandra
      - redis
    volumes:
      - ${APP_CODE_PATH_HOST}/kartotherian:/home/kartotherian
      - ${APP_CODE_PATH_HOST}/dependencies:/srv/dependencies
      - ${DATA_PATH_HOST}/imposm:/srv/imposm
      - ./kartotherian/sources.docker.yaml:/etc/opt/sources.docker.yaml
    tty: true
    networks:
      - frontend
      - backend

### PostgreSQL PostGis ##################################
  postgres-postgis:
    image: postgis/postgis:11-3.1
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    depends_on:
      - workspace
    networks:
      - backend

  ### Cassandra ##################################
  cassandra:
    image: cassandra:3.11.4  # Production version
    volumes:
      - ${DATA_PATH_HOST}/cassandra:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    networks:
      - backend

### Redis ##################################
  redis:
    image: redis:latest
    volumes:
        - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

### Graphite statsd ##################################
  statsd:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "8000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125"
      - "8126:8126"
    restart: always
    networks:
      - backend

### Tegola ##################################
  tegola:
    build: ./tegola
#    build: https://github.com/go-spatial/tegola.git#v0.14.x
    environment:
      - TEGOLA_BROKER_URL=redis://redis:6379
      - TEGOLA_QUEUE_NAME=pregen
      - TEGOLA_PATH=/opt/tegola
      - TEGOLA_CONFIG_PATH=/etc/tegola.toml
    volumes:
      - ./tegola/tegola.toml:/etc/tegola.toml
      - ./tegola/pregenerate-maps-tile.sh:/etc/pregenerate-maps-tile.sh
      - ${DATA_PATH_HOST}/tegola/cache:/etc/cache
    ports:
      - "${TEGOLA_PORT}:8080"
    networks:
      - backend
    command: serve --config /etc/tegola.toml

### Maputnik ##################################
  maputnik:
    image: maputnik/editor:latest
    ports:
      - "${MAPUTNIK_PORT}:8888"
    networks:
      - frontend
      - backend
